/**
 * Created by sabir on 19.07.17.
 */


//users
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const LOAD_USERS = 'LOAD_USERS'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL'

export const SELECT_USER = 'SELECT_USER'
export const UNSELECT_USER = 'UNSELECT_USER'


export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'


export const INITIALIZE_AUTH = 'INITIALIZE_AUTH'
export const INITIALIZE_AUTH_SUCCESS = 'INITIALIZE_AUTH_SUCCESS'
export const INITIALIZE_AUTH_FAIL = 'INITIALIZE_AUTH_FAIL'

export const SEARCH_USERS = 'SEARCH_USERS'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL'


//links
export const LOAD_USER_LINKS = 'LOAD_USER_LINKS'
export const LOAD_USER_LINKS_SUCCESS = 'LOAD_USER_LINKS_SUCCESS'
export const LOAD_USER_LINKS_FAIL = 'LOAD_USER_LINKS_FAIL'

export const CREATE_USER_LINK = 'CREATE_USER_LINK'
export const CREATE_USER_LINK_SUCCESS = 'CREATE_USER_LINK_SUCCESS'
export const CREATE_USER_LINK_FAIL = 'CREATE_USER_LINK_FAIL'

export const UPDATE_USER_LINK = 'UPDATE_USER_LINK'
export const UPDATE_USER_LINK_SUCCESS = 'UPDATE_USER_LINK_SUCCESS'
export const UPDATE_USER_LINK_FAIL = 'UPDATE_USER_LINK_FAIL'

export const DELETE_USER_LINK = 'DELETE_USER_LINK'
export const DELETE_USER_LINK_SUCCESS = 'DELETE_USER_LINK_SUCCESS'
export const DELETE_USER_LINK_FAIL = 'DELETE_USER_LINK_FAIL'

export const LOAD_FORMS = 'LOAD_FORMS'
export const LOAD_FORMS_SUCCESS = 'LOAD_FORMS_SUCCESS'
export const LOAD_FORMS_FAIL = 'LOAD_FORMS_FAIL'

export const CREATE_FORM = 'CREATE_FORM'
export const CREATE_FORM_SUCCESS = 'CREATE_FORM_SUCCESS'
export const CREATE_FORM_FAIL = 'CREATE_FORM_FAIL'

export const UPDATE_FORM = 'UPDATE_FORM'
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS'
export const UPDATE_FORM_FAIL = 'UPDATE_FORM_FAIL'

export const DELETE_FORM = 'DELETE_FORM'
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS'
export const DELETE_FORM_FAIL = 'DELETE_FORM_FAIL'


//realtime
export const PUSHER_MESSAGE_RECEIVED = 'PUSHER_MESSAGE_RECEIVED'

export const SEND_EVENT = 'SEND_EVENT'
export const SEND_EVENT_SUCCESS = 'SEND_EVENT_SUCCESS'
export const SEND_EVENT_FAIL = 'SEND_EVENT_FAIL'


//aircrafts
export const LOAD_AIRCRAFTS = 'LOAD_AIRCRAFTS'
export const LOAD_AIRCRAFTS_SUCCESS = 'LOAD_AIRCRAFTS_SUCCESS'
export const LOAD_AIRCRAFTS_FAIL = 'LOAD_AIRCRAFTS_FAIL'

export const CREATE_AIRCRAFT = 'CREATE_AIRCRAFT'
export const CREATE_AIRCRAFT_SUCCESS = 'CREATE_AIRCRAFT_SUCCESS'
export const CREATE_AIRCRAFT_FAIL = 'CREATE_AIRCRAFT_FAIL'

export const UPDATE_AIRCRAFT = 'UPDATE_AIRCRAFT'
export const UPDATE_AIRCRAFT_SUCCESS = 'UPDATE_AIRCRAFT_SUCCESS'
export const UPDATE_AIRCRAFT_FAIL = 'UPDATE_AIRCRAFT_FAIL'

export const DELETE_AIRCRAFT = 'DELETE_AIRCRAFT'
export const DELETE_AIRCRAFT_SUCCESS = 'DELETE_AIRCRAFT_SUCCESS'
export const DELETE_AIRCRAFT_FAIL = 'DELETE_AIRCRAFT_FAIL'

export const SELECT_AIRCRAFT = 'SELECT_AIRCRAFT'


//organizations
export const LOAD_ORGANIZATIONS = 'LOAD_ORGANIZATIONS'
export const LOAD_ORGANIZATIONS_SUCCESS = 'LOAD_ORGANIZATIONS_SUCCESS'
export const LOAD_ORGANIZATIONS_FAIL = 'LOAD_ORGANIZATIONS_FAIL'

export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
export const CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS'
export const CREATE_ORGANIZATION_FAIL = 'CREATE_ORGANIZATION_FAIL'

export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS'
export const UPDATE_ORGANIZATION_FAIL = 'UPDATE_ORGANIZATION_FAIL'

export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS'
export const DELETE_ORGANIZATION_FAIL = 'DELETE_ORGANIZATION_FAIL'

//sessions


//sessions
export const LOAD_SESSIONS = 'LOAD_SESSIONS'
export const LOAD_SESSIONS_SUCCESS = 'LOAD_SESSIONS_SUCCESS'
export const LOAD_SESSIONS_FAIL = 'LOAD_SESSIONS_FAIL'

export const LOAD_SESSION_DATA = 'LOAD_SESSION_DATA'
export const LOAD_SESSION_DATA_SUCCESS = 'LOAD_SESSION_DATA_SUCCESS'
export const LOAD_SESSION_DATA_FAIL = 'LOAD_SESSION_DATA_FAIL'

export const LOAD_MANY_SESSIONS_DATA = 'LOAD_MANY_SESSIONS_DATA'
export const LOAD_MANY_SESSIONS_DATA_SUCCESS = 'LOAD_MANY_SESSIONS_DATA_SUCCESS'
export const LOAD_MANY_SESSIONS_DATA_FAIL = 'LOAD_MANY_SESSIONS_DATA_FAIL'

export const SAVE_SESSION_POINTS = 'SAVE_SESSION_POINTS'
export const SAVE_SESSION_POINTS_SUCCESS = 'SAVE_SESSION_POINTS_SUCCESS'
export const SAVE_SESSION_POINTS_FAIL = 'SAVE_SESSION_POINTS_FAIL'


//select / unselect
export const SELECT_SESSION = 'SELECT_SESSION'
export const UNSELECT_SESSION = 'UNSELECT_SESSION'


//GPS
export const ON_GPS_POINTS_RECEIVED = 'ON_GPS_POINTS_RECEIVED'

//gps
export const INIT_GPS = 'INIT_GPS'
export const INIT_GPS_SUCCESS = 'INIT_GPS_SUCCESS'
export const INIT_GPS_FAIL = 'INIT_GPS_FAIL'

//flight
export const START_FLIGHT = 'START_FLIGHT'
export const STOP_FLIGHT = 'STOP_FLIGHT'

//tab
export const SELECT_NAVIGATION_TAB = 'SELECT_NAVIGATION_TAB'

//chat

//messages
export const LOAD_MESSAGES = 'LOAD_MESSAGES'
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS'
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL'

export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS'
export const CREATE_MESSAGE_FAIL = 'CREATE_MESSAGE_FAIL'

export const VIEW_MESSAGES = 'VIEW_MESSAGES'
export const VIEW_MESSAGES_SUCCESS = 'VIEW_MESSAGES_SUCCESS'
export const VIEW_MESSAGES_FAIL = 'VIEW_MESSAGES_FAIL'

//
export const SELECT_CHAT_USER = 'SELECT_CHAT_USER'
export const UNSELECT_CHAT_USER = 'UNSELECT_CHAT_USER'

//measurements
export const CREATE_MEASUREMENT = 'CREATE_MEASUREMENT'
export const CREATE_MEASUREMENT_SUCCESS = 'CREATE_MEASUREMENT_SUCCESS'
export const CREATE_MEASUREMENT_FAIL = 'CREATE_MEASUREMENT_FAIL'

export const UPDATE_MEASUREMENT = 'UPDATE_MEASUREMENT'
export const UPDATE_MEASUREMENT_SUCCESS = 'UPDATE_MEASUREMENT_SUCCESS'
export const UPDATE_MEASUREMENT_FAIL = 'UPDATE_MEASUREMENT_FAIL'

export const DELETE_MEASUREMENT = 'DELETE_MEASUREMENT'
export const DELETE_MEASUREMENT_SUCCESS = 'DELETE_MEASUREMENT_SUCCESS'
export const DELETE_MEASUREMENT_FAIL = 'DELETE_MEASUREMENT_FAIL'

export const LOAD_MEASUREMENTS = 'LOAD_MEASUREMENTS'
export const LOAD_MEASUREMENTS_SUCCESS = 'LOAD_MEASUREMENTS_SUCCESS'
export const LOAD_MEASUREMENTS_FAIL = 'LOAD_MEASUREMENTS_FAIL'

export const SELECT_MEASUREMENT = 'SELECT_MEASUREMENT'
export const UNSELECT_MEASUREMENT = 'UNSELECT_MEASUREMENT'

export const SET_MEASUREMENTS_VIEW_RANGE = 'SET_MEASUREMENTS_VIEW_RANGE'

export const SET_NEW_MEASUREMENT_TYPE = 'SET_NEW_MEASUREMENT_TYPE'
export const CLOSE_MEASUREMENT_FORM = 'CLOSE_MEASUREMENT_FORM'

export const SET_STATS_RANGE = 'SET_STATS_RANGE'



//UI
//todo(@mitya):
export const SET_SCREEN = 'SET_SCREEN'
export const SET_MODE = 'SET_MODE'


